[workspace]
name = "robostack"
description = "Development environment for RoboStack ROS packages"
channels = ["robostack-humble", "conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "linux-aarch64"]

[dependencies]
python = ">=3.11.14,<3.12"

# Build tools
compilers = ">=1.11.0,<2"
cmake = ">=4.2.0,<5"
pkg-config = ">=0.29.2,<0.30"
make = ">=4.4.1,<5"
ninja = ">=1.13.2,<2"

# ROS specific tools
rosdep = ">=0.26.0,<0.27"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-desktop = ">=0.10.0,<0.11"
catkin_tools = ">=0.8.2,<0.10"
ros-humble-tf2-geometry-msgs = ">=0.25.14,<0.26"
ros-humble-nav2-rviz-plugins = ">=1.1.18,<2"
ros-humble-slam-toolbox = ">=2.6.10,<3"
ros-humble-nav2-simple-commander = ">=1.1.18,<2"
ros-humble-pcl-ros = ">=2.4.5,<3"
ros-humble-foxglove-bridge = ">=0.8.5,<0.9"
ros-humble-nav2-bringup = ">=1.1.18,<2"
ros-humble-pointcloud-to-laserscan = ">=2.0.1,<3"
ros-humble-twist-mux = ">=4.3.0,<5"
ros-humble-rosidl-generator-dds-idl = ">=0.8.1,<0.9"
uvicorn = ">=0.38.0,<0.39"

[pypi-dependencies]
aiortc = "==1.9.0"
open3d = "*"
paho-mqtt = "*"
python-dotenv = "*"
wasmtime = "*"
pycryptodome = "*"
opencv-python = "*"
pydub = "*"
numpy = "==1.26.4"
